name: CD

on:
  release:
    types:
      - prereleased
      - released

jobs:
  push:
    name: Push to version branches
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Push to stable branch
        run: |
          git push origin HEAD:refs/heads/stable --force
      - name: Push to matching minor version branch
        env:
          TAG: ${{ github.ref_name }}
        run: |
          re='^([0-9]+)\.([0-9]+)\.[0-9]+'
          if [[ $TAG =~ $re ]]; then
            MINOR_VERSION_BRANCH="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.x"
            git push origin HEAD:refs/heads/$MINOR_VERSION_BRANCH --force
          fi
